### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(PR_projectContent)
add_subdirectory(PR_project)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    PR_projectContentplugin
    PR_projectplugin)